USE u487987634_panaderia_kiss;

CREATE TABLE usuarios(
	IdUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nombre VARCHAR(30) NOT NULL,
	AP VARCHAR(30) NOT NULL,
	AM VARCHAR(30) NOT NULL,
	FechaN DATE NOT NULL,
	ROL ENUM('VENDEDOR','ADMINISTRADOR') NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Contrasenia VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE productos(
	IdProducto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nombre VARCHAR(20) NOT NULL,
	Costo DECIMAL(10,2) NOT NULL,
	CantDis INT NOT NULL COMMENT 'Cantidad en stock',
	Imagen varchar(100) NULL COMMENT 'Nombre de la imagen relacionada con el Producto',
	Descrip TEXT NOT NULL
)ENGINE=InnoDB;

CREATE TABLE provedores(
	IdProv INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Descrip TEXT NOT NULL,
	Calle VARCHAR(40) NOT NULL,
	Num VARCHAR(10) NOT NULL,
	Negocio VARCHAR(30) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Contrasenia VARCHAR(100) NOT NULL,
	Estado TINYINT(1) NOT NULL COMMENT 'Estado activo o inactivo del proovedor'
	)ENGINE=InnoDB;

CREATE TABLE contactos(
	IdContac INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Nombre VARCHAR(30) NOT NULL,
	AP VARCHAR(30) NOT NULL,
	AM VARCHAR(30) NULL,
	Tel VARCHAR(20) NULL NULL,
	Encargo VARCHAR(20) NULL,
	Email VARCHAR(50) NOT NULL,
	IdProv INT NOT NULL,
	Contrasenia VARCHAR(100),
	FOREIGN KEY (IdProv) REFERENCES provedores(IdProv) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE ventas(
	IdVenta INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Cantidad INT NOT NULL,
	Total DECIMAL(10,2) NOT NULL,
	Fecha DATE NOT NULL,
	IdUsuario INT NOT  NULL,
	IdProv INT NOT NULL,
	FOREIGN KEY (IdUsuario) REFERENCES usuarios(IdUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdProv) REFERENCES provedores(IdProv) ON DELETE CASCADE ON UPDATE CASCADE
	)ENGINE=InnoDB;

CREATE TABLE reportes(
	IdReporte INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Fecha DATE NOT NULL,
	IngresoTotal DECIMAL(10,2) NOT NULL 
	)ENGINE = InnoDB;

CREATE TABLE cortes(
	IdCorte INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Cantidad DECIMAL(5,2) NOT NULL,
	Fecha DATE NOT NULL,
	IdReporte INT NOT NULL,
	IdUsuario INT NOT NULL,
	FOREIGN KEY (IdReporte) REFERENCES reportes(IdReporte) ON DELETE CASCADE ON UPDATE CASCADE
	)ENGINE= InnoDB;

CREATE TABLE Rep_Vent(
	IdReporte INT NOT NULL,
	IdVenta INT NOT NULL,
	FOREIGN KEY (IdReporte) REFERENCES reportes(IdReporte) ON  DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdVenta) REFERENCES ventas(IdVenta) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(IdReporte,IdVenta)
)ENGINE = InnoDB;

CREATE TABLE Prod_Vent(
	IdProducto INT NOT NULL,
	IdVenta INT NOT NULL,
	Cantidad INT NOT NULL,
	Subtotal DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (IdProducto) REFERENCES productos(IdProducto) ON  DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IdVenta) REFERENCES ventas(IdVenta) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(IdProducto,IdVenta)
)ENGINE = InnoDB;